### ISSUE TITLE
The sleep module is not included in dependencies

### ISSUE THREAD

**Issue by rodnolan** [dmamalis/apollopro#1]
Following the README instructions, I get the following error:

```
➜  apollopro git:(master) ✗ yarn start
yarn run v1.21.1
$ node readout.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'sleep'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/rodn/GitHub/rodnolan/apollopro/readout.js:1:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  apollopro git:(master) ✗ 
``` 

which makes sense because sleep is not included in `package.json`. I ran `yarn add sleep` and then `yarn start` worked as expected.

Updating the dependencies list with 
```
"sleep": "^6.1.0"
```
should solve this.

**Comment by dmamalis** [comment]
fixed :-)
